import type { Metadata } from "next";
import { Language, languages } from "@/lib/i18n/settings";
import "./globals.css";
import { Header } from "@/components/ui/header";
import { MainProvider } from "@/provider/mainProvider";

type Params = Promise<{ locale: Language }>;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ locale: lng }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Params;
}>) {
  const getParams = await params;
  const { locale } = getParams;

  return (
    <html
      lang={locale}
      dir={locale === "fa" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning={true}
      >
        <MainProvider lng={locale}>
          <Header />
          {children}
        </MainProvider>
      </body>
    </html>
  );
}
