import type { Metadata } from "next";
import { Language, languages } from "@/lib/i18n/settings";
import "./globals.css";
import { Header } from "@/components/ui/header";
import { MainProvider } from "@/provider/mainProvider";
import { ConditionalRenderer } from "@/components/shared/ConditionalRenderer";
import MobileComponents from "@/components/ui/header/mobile";
import { inter, yekanbakh } from "@/font";
import { cn } from "@/utils/cn";

type Params = Promise<{ locale: Language }>;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ locale: lng }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Params;
}>) {
  const getParams = await params;
  const { locale } = getParams;

  return (
    <html
      lang={locale}
      dir={locale === "fa" ? "rtl" : "ltr"}
      className={cn("font-inter", "font-yekanbakh")}
      suppressHydrationWarning
      style={{
        fontFamily: locale === "en" ? inter.variable : yekanbakh.variable,
      }}
    >
      <body suppressHydrationWarning={true}>
        <MainProvider lng={locale}>
          <ConditionalRenderer
            desktop={<Header />}
            mobile={<MobileComponents />}
          />
          <main className="container mx-auto px-4 md:px-8 grow">
            {children}
          </main>
        </MainProvider>
      </body>
    </html>
  );
}
